const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Plugins.TextBox,
		C3.Behaviors.Anchor,
		C3.Plugins.TiledBg,
		C3.Behaviors.Rotate,
		C3.Behaviors.Sin,
		C3.Behaviors.scrollto,
		C3.Plugins.Text,
		C3.Plugins.Touch,
		C3.Plugins.Keyboard,
		C3.Plugins.Mouse,
		C3.Behaviors.EightDir,
		C3.Behaviors.destroy,
		C3.Plugins.Browser,
		C3.Plugins.Date,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Plugins.System.Cnds.CompareBoolVar,
		C3.Plugins.Touch.Cnds.OnTouchObject,
		C3.Plugins.System.Acts.SetGroupActive,
		C3.Plugins.System.Acts.CreateObject,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.System.Acts.SetBoolVar,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.TextBox.Acts.SetWidth,
		C3.Plugins.System.Exps.viewportwidth,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.TextBox.Acts.SetCSSStyle,
		C3.Plugins.TextBox.Acts.SetEnabled,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.TextBox.Acts.SetVisible,
		C3.Plugins.Sprite.Acts.SetOpacity,
		C3.Plugins.Sprite.Exps.Opacity,
		C3.Plugins.Sprite.Acts.SetX,
		C3.Plugins.Sprite.Exps.X,
		C3.Behaviors.Anchor.Acts.SetEnabled,
		C3.Plugins.TextBox.Acts.SetText,
		C3.Plugins.System.Cnds.Compare,
		C3.Plugins.TextBox.Exps.Text,
		C3.Plugins.Browser.Acts.Alert,
		C3.Plugins.Date.Exps.GetDate,
		C3.Plugins.Date.Exps.Now,
		C3.Plugins.Date.Exps.GetMonth,
		C3.Plugins.Date.Exps.GetYear,
		C3.Plugins.System.Cnds.Else,
		C3.Plugins.TextBox.Cnds.CompareText,
		C3.Plugins.Sprite.Acts.SetInstanceVar,
		C3.Plugins.System.Acts.SetLayerOpacity,
		C3.Plugins.System.Acts.ToggleBoolVar,
		C3.Plugins.Sprite.Acts.SetAngle,
		C3.Plugins.Sprite.Exps.Angle,
		C3.Plugins.Sprite.Acts.SetAnimFrame,
		C3.Plugins.TiledBg.Acts.SetOpacity,
		C3.Plugins.TiledBg.Exps.Opacity,
		C3.Plugins.System.Exps.layeropacity,
		C3.Plugins.Keyboard.Cnds.OnKey,
		C3.Plugins.System.Acts.ResetGlobals,
		C3.Plugins.System.Acts.RestartLayout,
		C3.Behaviors.EightDir.Acts.SimulateControl
	];
};
self.C3_JsPropNameTable = [
	{last_payBtn: 0},
	{no_payBtn: 0},
	{Anchor: 0},
	{last_pay: 0},
	{noPay: 0},
	{Rotate: 0},
	{Sine: 0},
	{loginBackground: 0},
	{ScrollTo: 0},
	{freg: 0},
	{var: 0},
	{login_btn: 0},
	{forgot_pass_btn: 0},
	{logo_small: 0},
	{login_Input: 0},
	{password_input: 0},
	{version_text: 0},
	{Touch: 0},
	{Display: 0},
	{loading_logo: 0},
	{byBohunIvan: 0},
	{loading_circle: 0},
	{just_text: 0},
	{div: 0},
	{realestate: 0},
	{savemoney: 0},
	{lighting: 0},
	{admin_text: 0},
	{startPos: 0},
	{menuBtn: 0},
	{select_point: 0},
	{menuBlock: 0},
	{TiledBackground: 0},
	{logo_small2: 0},
	{nameText: 0},
	{zoneNumber: 0},
	{infoBtn_menu: 0},
	{settingsBtn_menu: 0},
	{assetsBtn_menu: 0},
	{exitBtn_menu: 0},
	{Keyboard: 0},
	{Mouse: 0},
	{"8Direction": 0},
	{DestroyOutsideLayout: 0},
	{up_kulise: 0},
	{loginBackground2: 0},
	{lich: 0},
	{Browser: 0},
	{Date: 0},
	{menu_btns: 0},
	{cursor_style_on_btns: 0},
	{rent_pay_noPay: 0},
	{last_pokas: 0},
	{elektr_pokaz: 0},
	{menuState: 0},
	{username: 0}
];

self.InstanceType = {
	last_payBtn: class extends self.ISpriteInstance {},
	no_payBtn: class extends self.ISpriteInstance {},
	last_pay: class extends self.ITextInputInstance {},
	noPay: class extends self.ITextInputInstance {},
	loginBackground: class extends self.ITiledBackgroundInstance {},
	freg: class extends self.ISpriteInstance {},
	login_btn: class extends self.ISpriteInstance {},
	forgot_pass_btn: class extends self.ISpriteInstance {},
	logo_small: class extends self.ISpriteInstance {},
	login_Input: class extends self.ITextInputInstance {},
	password_input: class extends self.ITextInputInstance {},
	version_text: class extends self.ITextInstance {},
	Touch: class extends self.IInstance {},
	Display: class extends self.ISpriteInstance {},
	loading_logo: class extends self.ISpriteInstance {},
	byBohunIvan: class extends self.ISpriteInstance {},
	loading_circle: class extends self.ISpriteInstance {},
	just_text: class extends self.ITextInstance {},
	div: class extends self.ITiledBackgroundInstance {},
	realestate: class extends self.ISpriteInstance {},
	savemoney: class extends self.ISpriteInstance {},
	lighting: class extends self.ISpriteInstance {},
	admin_text: class extends self.ITextInstance {},
	menuBtn: class extends self.ISpriteInstance {},
	select_point: class extends self.ISpriteInstance {},
	menuBlock: class extends self.ITiledBackgroundInstance {},
	TiledBackground: class extends self.ITiledBackgroundInstance {},
	logo_small2: class extends self.ISpriteInstance {},
	nameText: class extends self.ITextInstance {},
	zoneNumber: class extends self.ITextInstance {},
	infoBtn_menu: class extends self.ISpriteInstance {},
	settingsBtn_menu: class extends self.ISpriteInstance {},
	assetsBtn_menu: class extends self.ISpriteInstance {},
	exitBtn_menu: class extends self.ISpriteInstance {},
	Keyboard: class extends self.IInstance {},
	Mouse: class extends self.IInstance {},
	up_kulise: class extends self.ITiledBackgroundInstance {},
	loginBackground2: class extends self.ITiledBackgroundInstance {},
	lich: class extends self.ITextInputInstance {},
	Browser: class extends self.IInstance {},
	Date: class extends self.IInstance {},
	menu_btns: class extends self.ISpriteInstance {},
	cursor_style_on_btns: class extends self.ISpriteInstance {}
}